### PR TITLE
Second attempt to fix context hashing

### LINKED ISSUE #5: context digest computation is wrong
It needs to take into account the Dockerfile too. Or there needs to be a separate Dockerfile digest that it tracks.

### PR DESCRIPTION
**Pull request by benesch**
@antifuchs I didn't test this, but I'm hopeful it does the trick!

Fixes #5

### CODE REVIEW

**Comment by antifuchs** [comment]
I pushed a thing up to make the file-hashing thing a bit more uniform & account for file modes as well. WDYT?

**Review by antifuchs — APPROVED** [review]
(partially self-approving)

In my tests, this is pretty much stable, not sure why it looked like the hash was not stable. Anyway, I think this fixes the issue & can go out as 0.1.5

**Review by benesch — COMMENTED** [review]
LGTM too!

**Comment by benesch** [comment]
(I'm not planning to merge + release, just FYI!)

**Pull request merged**
